version: 2

sources:
  - name: tpch_raw
    description: tpc-h dataset from snowflake share
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF10
    tables:
      - name: customer
      - name: nation

models:
    - name: customer_per_region

