version: 2

sources:
  - name: tpch_raw
    description: tpc-h dataset from snowflake share
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
    tables:
      - name: customer
      - name: nation
      - name: region
      - name: orders

models:
    - name: customer_per_nation

    - name: customer_per_region
      columns:
        - name: R_NAME
          tests:
            - relationships:
                to: source('tpch_raw','region')
                field: R_NAME

    - name: customer_incr
      columns:
        - name: O_ORDERKEY
          tests:
            - unique
            - not_null


